# Generated by Django 6.0.4 on 2026-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(related_name='subjects', to='classes.class')),
                ('teachers', models.ManyToManyField(related_name='subjects_taught', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
